use std::fs;
use std::io;
use std::path::Path;
use std::process::Command;

fn main() {
    rerun_if_changed_recursive(Path::new("assets"));
    rerun_if_changed_recursive(Path::new("src"));
    rerun_if_changed_recursive(Path::new("frontend/locales"));
    rerun_if_changed_recursive(Path::new("frontend/src"));
    rerun_if_changed_recursive(Path::new("frontend/public"));
    println!("cargo:rerun-if-changed=frontend/index.html");
    println!("cargo:rerun-if-changed=frontend/package.json");
    println!("cargo:rerun-if-changed=frontend/package-lock.json");
    println!("cargo:rerun-if-changed=frontend/vite.config.ts");
    println!("cargo:rerun-if-changed=frontend/tsconfig.json");
    println!("cargo:rerun-if-changed=frontend/tsconfig.node.json");
    println!("cargo:rerun-if-changed=frontend/postcss.config.cjs");
    println!("cargo:rerun-if-changed=frontend/tailwind.config.cjs");
    println!("cargo:rerun-if-env-changed=KOSHELF_SKIP_NPM_INSTALL");
    println!("cargo:rerun-if-env-changed=KOSHELF_SKIP_REACT_BUILD");
    println!("cargo:rerun-if-env-changed=KOSHELF_SKIP_FONT_DOWNLOAD");
    println!("cargo:rerun-if-env-changed=KOSHELF_FONT_CACHE_DIR");

    let skip_npm_install = env_flag("KOSHELF_SKIP_NPM_INSTALL");
    let skip_react_build = env_flag("KOSHELF_SKIP_REACT_BUILD");
    let skip_font_download = env_flag("KOSHELF_SKIP_FONT_DOWNLOAD");

    let out_dir = std::env::var("OUT_DIR").unwrap();

    // Generate a compact locale manifest for CLI language listing.
    generate_locale_manifest(&out_dir);

    // Build React + Vite frontend.
    compile_react_frontend(skip_npm_install, skip_react_build);

    // Download and embed fonts for SVG rendering
    download_fonts(&out_dir, skip_font_download);
}

fn generate_locale_manifest(out_dir: &str) {
    let locales_dir = Path::new("frontend").join("locales");
    let output_path = Path::new(out_dir).join("locale_manifest.rs");

    let mut languages = std::collections::BTreeMap::<String, String>::new();

    if !locales_dir.exists() {
        panic!("Locales directory is missing: {}", locales_dir.display());
    }

    let entries = fs::read_dir(&locales_dir).unwrap_or_else(|error| {
        panic!(
            "Failed to read locales directory {}: {}",
            locales_dir.display(),
            error
        )
    });

    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path.extension().and_then(|ext| ext.to_str()) != Some("ftl") {
            continue;
        }

        let filename = match path.file_name().and_then(|n| n.to_str()) {
            Some(name) => name,
            None => continue,
        };
        let stem = filename.trim_end_matches(".ftl");
        let content = fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!("Failed to read locale file {}: {}", path.display(), error)
        });

        let mut lang_name: Option<String> = None;
        let mut lang_dialect: Option<String> = None;

        for line in content.lines() {
            let trimmed = line.trim();
            if !trimmed.starts_with('-') {
                continue;
            }

            if let Some((key, value)) = trimmed.split_once('=') {
                match key.trim() {
                    "-lang-name" => lang_name = Some(value.trim().to_string()),
                    "-lang-dialect" => lang_dialect = Some(value.trim().to_string()),
                    _ => {}
                }
            }
        }

        let code = lang_dialect.unwrap_or_else(|| stem.to_string());
        let name = lang_name.unwrap_or_else(|| format!("Unknown ({})", stem));
        languages.entry(code).or_insert(name);
    }

    if languages.is_empty() {
        panic!(
            "No locale metadata found while generating manifest from {}",
            locales_dir.display()
        );
    }

    let mut source = String::from(
        "// @generated by build.rs\npub const SUPPORTED_LANGUAGES: &[(&str, &str)] = &[\n",
    );
    for (code, name) in &languages {
        source.push_str(&format!("    ({:?}, {:?}),\n", code, name));
    }
    source.push_str("];\n");

    write_if_changed(&output_path, source.as_bytes())
        .unwrap_or_else(|e| panic!("Failed to write locale manifest {:?}: {}", output_path, e));
}

fn env_flag(name: &str) -> bool {
    matches!(
        std::env::var(name).as_deref(),
        Ok("1") | Ok("true") | Ok("TRUE") | Ok("yes") | Ok("YES") | Ok("on") | Ok("ON")
    )
}

fn rerun_if_changed_recursive(dir: &Path) {
    if !dir.exists() {
        return;
    }

    // Watch the directory entry too, so add/remove/rename can trigger rebuilds.
    if let Some(p) = dir.to_str() {
        println!("cargo:rerun-if-changed={}", p);
    }

    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            rerun_if_changed_recursive(&path);
        } else if path.is_file() {
            // Best-effort: only print paths Cargo can parse nicely.
            if let Some(p) = path.to_str() {
                println!("cargo:rerun-if-changed={}", p);
            }
        }
    }
}

fn write_if_changed(path: &Path, bytes: &[u8]) -> io::Result<bool> {
    match fs::read(path) {
        Ok(existing) if existing == bytes => Ok(false),
        _ => {
            fs::write(path, bytes)?;
            Ok(true)
        }
    }
}

/// Build the React+Vite frontend used by the runtime and static export paths.
fn compile_react_frontend(skip_npm_install: bool, skip_react_build: bool) {
    let frontend_dir = Path::new("frontend");
    let frontend_package = frontend_dir.join("package.json");

    if !frontend_package.exists() {
        eprintln!("No frontend/package.json found, skipping React frontend build");
        return;
    }

    if skip_react_build {
        eprintln!("Skipping React frontend build (KOSHELF_SKIP_REACT_BUILD=1)");
        return;
    }

    let frontend_lock = frontend_dir.join("package-lock.json");
    let frontend_node_modules = frontend_dir.join("node_modules");

    let should_install = !frontend_node_modules.exists()
        || (frontend_lock.exists()
            && frontend_node_modules
                .metadata()
                .and_then(|m| m.modified())
                .unwrap_or(std::time::SystemTime::UNIX_EPOCH)
                < frontend_lock
                    .metadata()
                    .and_then(|m| m.modified())
                    .unwrap_or(std::time::SystemTime::UNIX_EPOCH));

    if should_install {
        if skip_npm_install {
            panic!(
                "frontend/node_modules missing/outdated but npm install is disabled (KOSHELF_SKIP_NPM_INSTALL). \
                 Run `npm --prefix frontend ci`/`npm --prefix frontend install`, or unset the env var."
            );
        }

        eprintln!("Installing frontend npm dependencies...");
        let mut cmd = Command::new("npm");
        cmd.args(["--prefix", "frontend"]);
        if frontend_lock.exists() {
            cmd.arg("ci");
        } else {
            cmd.arg("install");
        }

        let install_output = cmd
            .output()
            .expect("Failed to install frontend npm dependencies.");
        if !install_output.status.success() {
            panic!(
                "frontend npm install failed:\nstdout: {}\nstderr: {}",
                String::from_utf8_lossy(&install_output.stdout),
                String::from_utf8_lossy(&install_output.stderr)
            );
        }
    }

    eprintln!("Building React frontend with Vite...");
    let build_output = Command::new("npm")
        .args(["--prefix", "frontend", "run", "build"])
        .output()
        .expect("Failed to run frontend build.");

    if !build_output.status.success() {
        panic!(
            "React frontend build failed:\nstdout: {}\nstderr: {}",
            String::from_utf8_lossy(&build_output.stdout),
            String::from_utf8_lossy(&build_output.stderr)
        );
    }

    let dist_dir = frontend_dir.join("dist");
    if !dist_dir.exists() {
        panic!("frontend build completed but dist directory was not found");
    }
    eprintln!("React frontend build completed: {}", dist_dir.display());
}

/// Download Gelasio font files for SVG rendering
/// Uses a shared cache directory so fonts are only downloaded once across all targets
fn download_fonts(out_dir: &str, skip_download: bool) {
    let fonts = [
        (
            "Gelasio-Regular.ttf",
            "https://fonts.gstatic.com/s/gelasio/v14/cIfiMaFfvUQxTTqS3iKJkLGbI41wQL8Ilycs.ttf",
        ),
        (
            "Gelasio-Italic.ttf",
            "https://fonts.gstatic.com/s/gelasio/v14/cIfsMaFfvUQxTTqS9Cu7b2nySBfeR6rA1M9v8zQ.ttf",
        ),
    ];

    // Use a shared cache directory in target/ so fonts are only downloaded once
    // across all target architectures during cross-compilation
    let cache_dir = std::env::var("KOSHELF_FONT_CACHE_DIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| Path::new("target").join(".font-cache"));
    fs::create_dir_all(&cache_dir).expect("Failed to create font cache directory");

    for (filename, url) in fonts {
        let cache_path = cache_dir.join(filename);
        let dest_path = Path::new(out_dir).join(filename);

        // Check if font is already in shared cache
        if cache_path.exists() {
            eprintln!("Font {} found in cache, copying to build dir", filename);
            let bytes = fs::read(&cache_path)
                .unwrap_or_else(|e| panic!("Failed to read cached font {}: {}", filename, e));
            let _wrote = write_if_changed(&dest_path, &bytes)
                .unwrap_or_else(|e| panic!("Failed to write font {}: {}", filename, e));
            continue;
        }

        if skip_download {
            panic!(
                "Font {} not found in cache and downloading is disabled (KOSHELF_SKIP_FONT_DOWNLOAD=1). \
                 Either unset that env var, or pre-populate the cache at {:?}.",
                filename, cache_dir
            );
        }

        eprintln!("Downloading font: {}...", filename);

        match ureq::get(url).call() {
            Ok(response) => {
                let bytes = match response.into_body().read_to_vec() {
                    Ok(b) => b,
                    Err(e) => panic!("Failed to read font data for {}: {}", filename, e),
                };

                // Save to shared cache
                fs::write(&cache_path, &bytes)
                    .unwrap_or_else(|e| panic!("Failed to cache font {}: {}", filename, e));

                // Copy to build output directory (but avoid rewriting identical output).
                let _wrote = write_if_changed(&dest_path, &bytes)
                    .unwrap_or_else(|e| panic!("Failed to write font {}: {}", filename, e));

                eprintln!(
                    "Font {} downloaded and cached ({} bytes)",
                    filename,
                    bytes.len()
                );
            }
            Err(e) => {
                panic!("Failed to download font {}: {}", filename, e);
            }
        }
    }

    eprintln!("Font files downloaded/verified successfully");
}
