use flate2::Compression;
use flate2::write::GzEncoder;
use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::io::Write;
use std::path::Path;
use std::process::Command;

#[derive(serde::Serialize)]
struct LicenseGroup {
    license: String,
    text: String,
    dependencies: Vec<LicenseDep>,
}

#[derive(serde::Serialize)]
struct LicenseDep {
    name: String,
    version: String,
}

fn main() {
    rerun_if_changed_recursive(Path::new("assets"));
    rerun_if_changed_recursive(Path::new("src"));
    rerun_if_changed_recursive(Path::new("frontend/locales"));
    rerun_if_changed_recursive(Path::new("frontend/src"));
    rerun_if_changed_recursive(Path::new("frontend/public"));
    println!("cargo:rerun-if-changed=frontend/index.html");
    println!("cargo:rerun-if-changed=frontend/package.json");
    println!("cargo:rerun-if-changed=frontend/package-lock.json");
    println!("cargo:rerun-if-changed=frontend/vite.config.ts");
    println!("cargo:rerun-if-changed=frontend/tsconfig.json");
    println!("cargo:rerun-if-changed=frontend/tsconfig.node.json");
    println!("cargo:rerun-if-changed=frontend/postcss.config.cjs");
    println!("cargo:rerun-if-changed=frontend/tailwind.config.cjs");
    println!("cargo:rerun-if-changed=about.toml");
    println!("cargo:rerun-if-changed=Cargo.lock");
    println!("cargo:rerun-if-env-changed=KOSHELF_SKIP_NPM_INSTALL");
    println!("cargo:rerun-if-env-changed=KOSHELF_SKIP_REACT_BUILD");
    println!("cargo:rerun-if-env-changed=KOSHELF_SKIP_LICENSE_GENERATION");

    let skip_npm_install = env_flag("KOSHELF_SKIP_NPM_INSTALL");
    let skip_react_build = env_flag("KOSHELF_SKIP_REACT_BUILD");
    let skip_license_generation = env_flag("KOSHELF_SKIP_LICENSE_GENERATION");

    let out_dir = std::env::var("OUT_DIR").unwrap();

    // Generate a compact locale manifest for CLI language listing.
    generate_locale_manifest(&out_dir);

    // Build React + Vite frontend, then pre-compress text assets for embedding.
    compile_react_frontend(skip_npm_install, skip_react_build);
    compress_frontend_dist(&out_dir);
    compress_fonts(&out_dir);

    // Generate third-party license text for embedding
    generate_licenses(&out_dir, skip_license_generation);
}

fn generate_locale_manifest(out_dir: &str) {
    let locales_dir = Path::new("frontend").join("locales");
    let output_path = Path::new(out_dir).join("locale_manifest.rs");

    let mut languages = std::collections::BTreeMap::<String, String>::new();

    if !locales_dir.exists() {
        panic!("Locales directory is missing: {}", locales_dir.display());
    }

    let entries = fs::read_dir(&locales_dir).unwrap_or_else(|error| {
        panic!(
            "Failed to read locales directory {}: {}",
            locales_dir.display(),
            error
        )
    });

    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path.extension().and_then(|ext| ext.to_str()) != Some("ftl") {
            continue;
        }

        let filename = match path.file_name().and_then(|n| n.to_str()) {
            Some(name) => name,
            None => continue,
        };
        let stem = filename.trim_end_matches(".ftl");
        let content = fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!("Failed to read locale file {}: {}", path.display(), error)
        });

        let mut lang_name: Option<String> = None;
        let mut lang_dialect: Option<String> = None;

        for line in content.lines() {
            let trimmed = line.trim();
            if !trimmed.starts_with('-') {
                continue;
            }

            if let Some((key, value)) = trimmed.split_once('=') {
                match key.trim() {
                    "-lang-name" => lang_name = Some(value.trim().to_string()),
                    "-lang-dialect" => lang_dialect = Some(value.trim().to_string()),
                    _ => {}
                }
            }
        }

        let code = lang_dialect.unwrap_or_else(|| stem.to_string());
        let name = lang_name.unwrap_or_else(|| format!("Unknown ({})", stem));
        languages.entry(code).or_insert(name);
    }

    if languages.is_empty() {
        panic!(
            "No locale metadata found while generating manifest from {}",
            locales_dir.display()
        );
    }

    let mut source = String::from(
        "// @generated by build.rs\npub const SUPPORTED_LANGUAGES: &[(&str, &str)] = &[\n",
    );
    for (code, name) in &languages {
        source.push_str(&format!("    ({:?}, {:?}),\n", code, name));
    }
    source.push_str("];\n");

    write_if_changed(&output_path, source.as_bytes())
        .unwrap_or_else(|e| panic!("Failed to write locale manifest {:?}: {}", output_path, e));
}

fn env_flag(name: &str) -> bool {
    matches!(
        std::env::var(name).as_deref(),
        Ok("1") | Ok("true") | Ok("TRUE") | Ok("yes") | Ok("YES") | Ok("on") | Ok("ON")
    )
}

fn rerun_if_changed_recursive(dir: &Path) {
    if !dir.exists() {
        return;
    }

    // Watch the directory entry too, so add/remove/rename can trigger rebuilds.
    if let Some(p) = dir.to_str() {
        println!("cargo:rerun-if-changed={}", p);
    }

    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            rerun_if_changed_recursive(&path);
        } else if path.is_file() {
            // Best-effort: only print paths Cargo can parse nicely.
            if let Some(p) = path.to_str() {
                println!("cargo:rerun-if-changed={}", p);
            }
        }
    }
}

fn write_if_changed(path: &Path, bytes: &[u8]) -> io::Result<bool> {
    match fs::read(path) {
        Ok(existing) if existing == bytes => Ok(false),
        _ => {
            fs::write(path, bytes)?;
            Ok(true)
        }
    }
}

/// Build the React+Vite frontend used by the runtime and static export paths.
fn compile_react_frontend(skip_npm_install: bool, skip_react_build: bool) {
    let frontend_dir = Path::new("frontend");
    let frontend_package = frontend_dir.join("package.json");

    if !frontend_package.exists() {
        eprintln!("No frontend/package.json found, skipping React frontend build");
        return;
    }

    if skip_react_build {
        eprintln!("Skipping React frontend build (KOSHELF_SKIP_REACT_BUILD=1)");
        return;
    }

    let frontend_lock = frontend_dir.join("package-lock.json");
    let frontend_node_modules = frontend_dir.join("node_modules");

    let should_install = !frontend_node_modules.exists()
        || (frontend_lock.exists()
            && frontend_node_modules
                .metadata()
                .and_then(|m| m.modified())
                .unwrap_or(std::time::SystemTime::UNIX_EPOCH)
                < frontend_lock
                    .metadata()
                    .and_then(|m| m.modified())
                    .unwrap_or(std::time::SystemTime::UNIX_EPOCH));

    if should_install {
        if skip_npm_install {
            panic!(
                "frontend/node_modules missing/outdated but npm install is disabled (KOSHELF_SKIP_NPM_INSTALL). \
                 Run `npm --prefix frontend ci`/`npm --prefix frontend install`, or unset the env var."
            );
        }

        eprintln!("Installing frontend npm dependencies...");
        let mut cmd = Command::new("npm");
        cmd.args(["--prefix", "frontend"]);
        if frontend_lock.exists() {
            cmd.arg("ci");
        } else {
            cmd.arg("install");
        }

        let install_output = cmd
            .output()
            .expect("Failed to install frontend npm dependencies.");
        if !install_output.status.success() {
            panic!(
                "frontend npm install failed:\nstdout: {}\nstderr: {}",
                String::from_utf8_lossy(&install_output.stdout),
                String::from_utf8_lossy(&install_output.stderr)
            );
        }
    }

    eprintln!("Building React frontend with Vite...");
    let build_output = Command::new("npm")
        .args(["--prefix", "frontend", "run", "build"])
        .output()
        .expect("Failed to run frontend build.");

    if !build_output.status.success() {
        panic!(
            "React frontend build failed:\nstdout: {}\nstderr: {}",
            String::from_utf8_lossy(&build_output.stdout),
            String::from_utf8_lossy(&build_output.stderr)
        );
    }

    let dist_dir = frontend_dir.join("dist");
    if !dist_dir.exists() {
        panic!("frontend build completed but dist directory was not found");
    }
    eprintln!("React frontend build completed: {}", dist_dir.display());
}

/// Copy `frontend/dist` to `$OUT_DIR/frontend_dist`, gzip-compressing text-based
/// assets to reduce the embedded binary size.
fn compress_frontend_dist(out_dir: &str) {
    let src = Path::new("frontend").join("dist");
    let dst = Path::new(out_dir).join("frontend_dist");

    if !src.exists() {
        eprintln!("frontend/dist not found, skipping frontend compression");
        return;
    }

    let mut total_original: u64 = 0;
    let mut total_compressed: u64 = 0;

    copy_dir_compressed(&src, &dst, &mut total_original, &mut total_compressed);

    if total_original > 0 {
        eprintln!(
            "Frontend assets: {} bytes -> {} bytes ({:.1}%)",
            total_original,
            total_compressed,
            (total_compressed as f64 / total_original as f64) * 100.0
        );
    }
}

fn copy_dir_compressed(
    src: &Path,
    dst: &Path,
    total_original: &mut u64,
    total_compressed: &mut u64,
) {
    fs::create_dir_all(dst).unwrap_or_else(|e| panic!("Failed to create {}: {}", dst.display(), e));

    for entry in fs::read_dir(src)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", src.display(), e))
        .flatten()
    {
        let path = entry.path();
        let dest = dst.join(entry.file_name());

        if path.is_dir() {
            copy_dir_compressed(&path, &dest, total_original, total_compressed);
        } else if path.is_file() {
            let data = fs::read(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e));
            let original_len = data.len() as u64;

            if is_compressible_extension(&path) {
                let mut encoder = GzEncoder::new(Vec::new(), Compression::best());
                encoder.write_all(&data).unwrap();
                let compressed = encoder.finish().unwrap();
                let compressed_len = compressed.len() as u64;

                *total_original += original_len;
                *total_compressed += compressed_len;

                let _ = write_if_changed(&dest, &compressed);
            } else {
                *total_original += original_len;
                *total_compressed += original_len;

                let _ = write_if_changed(&dest, &data);
            }
        }
    }
}

fn is_compressible_extension(path: &Path) -> bool {
    matches!(
        path.extension().and_then(|e| e.to_str()),
        Some("js" | "mjs" | "css" | "html" | "json" | "map" | "svg")
    )
}

/// Gzip-compress the embedded Gelasio font files to `$OUT_DIR`.
fn compress_fonts(out_dir: &str) {
    let fonts = [
        (
            "frontend/node_modules/@expo-google-fonts/gelasio/400Regular/Gelasio_400Regular.ttf",
            "Gelasio_400Regular.ttf.gz",
        ),
        (
            "frontend/node_modules/@expo-google-fonts/gelasio/400Regular_Italic/Gelasio_400Regular_Italic.ttf",
            "Gelasio_400Regular_Italic.ttf.gz",
        ),
    ];

    for (src, dst_name) in &fonts {
        let src_path = Path::new(src);
        if !src_path.exists() {
            eprintln!("Font not found: {src}, skipping compression");
            continue;
        }

        let data = fs::read(src_path)
            .unwrap_or_else(|e| panic!("Failed to read {}: {}", src_path.display(), e));

        let mut encoder = GzEncoder::new(Vec::new(), Compression::best());
        encoder.write_all(&data).unwrap();
        let compressed = encoder.finish().unwrap();

        eprintln!(
            "Font {}: {} bytes -> {} bytes ({:.1}%)",
            dst_name,
            data.len(),
            compressed.len(),
            (compressed.len() as f64 / data.len() as f64) * 100.0
        );

        let dest = Path::new(out_dir).join(dst_name);
        let _ = write_if_changed(&dest, &compressed);
    }
}

/// Returns the most recent modification time among the given paths, or None if
/// none of them exist.
fn newest_mtime(paths: &[&Path]) -> Option<std::time::SystemTime> {
    paths
        .iter()
        .filter_map(|p| fs::metadata(p).and_then(|m| m.modified()).ok())
        .max()
}

/// Generate third-party license text for embedding in the binary.
/// Combines Rust dependency licenses (via cargo-about) and frontend npm dependency
/// licenses (via license-checker-rseidelsohn).
fn generate_licenses(out_dir: &str, skip_generation: bool) {
    let output_path = Path::new(out_dir).join("LICENSES.json.gz");

    if skip_generation {
        eprintln!("Skipping license generation (KOSHELF_SKIP_LICENSE_GENERATION=1)");
        let mut encoder = GzEncoder::new(Vec::new(), Compression::best());
        encoder.write_all(b"[]").unwrap();
        let compressed = encoder.finish().unwrap();
        let _wrote = write_if_changed(&output_path, &compressed)
            .unwrap_or_else(|e| panic!("Failed to write license placeholder: {}", e));
        return;
    }

    // Skip regeneration when the output is already newer than all inputs.
    let input_paths: [&Path; 3] = [
        Path::new("Cargo.lock"),
        Path::new("about.toml"),
        Path::new("frontend/package-lock.json"),
    ];

    if let Ok(output_mtime) = fs::metadata(&output_path).and_then(|m| m.modified())
        && let Some(newest_input) = newest_mtime(&input_paths)
        && output_mtime >= newest_input
    {
        eprintln!("License output is up to date, skipping generation.");
        return;
    }

    let mut groups: Vec<LicenseGroup> = Vec::new();

    // ── Rust dependency licenses (cargo-about) ──────────────────────────
    // Filter by current build target so only actual dependencies are included
    // (e.g. no windows-* crates on macOS builds and vice versa).
    let target = std::env::var("TARGET").expect("TARGET env var not set");

    eprintln!("Generating Rust dependency licenses (target: {target})...");
    let cargo_about = Command::new("cargo")
        .args(["about", "generate", "--format", "json", "--target", &target])
        .output();

    let cargo_about_output = match cargo_about {
        Ok(result) if result.status.success() => result.stdout,
        Ok(result) => {
            let stderr = String::from_utf8_lossy(&result.stderr);
            let stdout = &result.stdout;
            if !stdout.is_empty() {
                eprintln!(
                    "cargo-about produced warnings but generated output:\n{}",
                    stderr
                );
                stdout.clone()
            } else {
                panic!("cargo-about failed to generate license output:\n{}", stderr);
            }
        }
        Err(e) => {
            panic!(
                "Failed to run cargo-about. Install it with: cargo install cargo-about\nError: {}",
                e
            );
        }
    };

    #[derive(serde::Deserialize)]
    struct CargoAboutOutput {
        licenses: Vec<CargoAboutLicense>,
    }
    #[derive(serde::Deserialize)]
    struct CargoAboutLicense {
        id: String,
        text: String,
        used_by: Vec<CargoAboutUsedBy>,
    }
    #[derive(serde::Deserialize)]
    struct CargoAboutUsedBy {
        #[serde(rename = "crate")]
        krate: CargoAboutCrate,
    }
    #[derive(serde::Deserialize)]
    struct CargoAboutCrate {
        name: String,
        version: String,
    }

    let parsed: CargoAboutOutput = serde_json::from_slice(&cargo_about_output)
        .expect("Failed to parse cargo-about JSON output");

    groups.extend(parsed.licenses.into_iter().map(|lic| {
        LicenseGroup {
            license: lic.id,
            text: lic.text,
            dependencies: lic
                .used_by
                .into_iter()
                .map(|u| LicenseDep {
                    name: u.krate.name,
                    version: u.krate.version,
                })
                .collect(),
        }
    }));

    // ── Frontend dependency licenses (license-checker-rseidelsohn) ─────
    let frontend_dir = Path::new("frontend");
    if frontend_dir.join("node_modules").exists() {
        eprintln!("Generating frontend dependency licenses...");
        groups.extend(collect_frontend_licenses());
    }

    // Merge groups that share identical (license, text) pairs.
    let mut merged: Vec<LicenseGroup> = Vec::new();
    for group in groups {
        if let Some(existing) = merged
            .iter_mut()
            .find(|g| g.license == group.license && g.text == group.text)
        {
            existing.dependencies.extend(group.dependencies);
        } else {
            merged.push(group);
        }
    }
    for group in &mut merged {
        group
            .dependencies
            .sort_by(|a, b| a.name.cmp(&b.name).then(a.version.cmp(&b.version)));
    }

    let json = serde_json::to_string(&merged).expect("Failed to serialize license data");

    let mut encoder = GzEncoder::new(Vec::new(), Compression::best());
    encoder.write_all(json.as_bytes()).unwrap();
    let compressed = encoder.finish().unwrap();

    eprintln!(
        "License data: {} bytes JSON -> {} bytes gzip ({:.1}%)",
        json.len(),
        compressed.len(),
        (compressed.len() as f64 / json.len() as f64) * 100.0
    );

    // Always write (not write_if_changed) to update mtime for the cache check.
    fs::write(&output_path, &compressed)
        .unwrap_or_else(|e| panic!("Failed to write compressed license file: {}", e));

    eprintln!("License generation completed: {}", output_path.display());
}

/// Parse the `accepted` list from about.toml (shared with cargo-about).
fn accepted_licenses() -> Vec<String> {
    let content = fs::read_to_string("about.toml").expect("Failed to read about.toml");
    let toml: toml::Value = toml::from_str(&content).expect("Failed to parse about.toml");

    toml["accepted"]
        .as_array()
        .expect("about.toml must contain an 'accepted' array")
        .iter()
        .map(|v| {
            v.as_str()
                .expect("Each accepted license must be a string")
                .to_string()
        })
        .collect()
}

fn collect_frontend_licenses() -> Vec<LicenseGroup> {
    let only_allow = accepted_licenses().join(";");

    let result = Command::new("npx")
        .args([
            "license-checker-rseidelsohn",
            "--production",
            "--excludePackages",
            "koshelf-frontend",
            "--onlyAllow",
            &only_allow,
            "--json",
        ])
        .current_dir("frontend")
        .output();

    let result = match result {
        Ok(r) => r,
        Err(e) => panic!(
            "Failed to run license-checker-rseidelsohn. \
             Install it with: npm --prefix frontend install --save-dev license-checker-rseidelsohn\n\
             Error: {}",
            e
        ),
    };

    if !result.status.success() {
        panic!(
            "Frontend license check failed (a dependency may use a disallowed license):\n{}",
            String::from_utf8_lossy(&result.stderr)
        );
    }

    let json: serde_json::Value =
        serde_json::from_slice(&result.stdout).expect("Failed to parse license-checker JSON");

    let packages = json
        .as_object()
        .expect("Expected JSON object from license-checker");

    // Group packages by their license text to avoid repetition.
    let mut groups: BTreeMap<String, (String, Option<String>, Vec<LicenseDep>)> = BTreeMap::new();

    for (pkg_id, info) in packages {
        let license_id = info["licenses"].as_str().unwrap_or("Unknown").to_string();

        // Read the actual license file if it exists and is not a README fallback.
        let license_text = info["licenseFile"]
            .as_str()
            .filter(|p| {
                let name = p.rsplit('/').next().unwrap_or("").to_lowercase();
                name.starts_with("licen") || name.starts_with("copying")
            })
            .and_then(|p| fs::read_to_string(p).ok())
            .map(|t| t.trim().to_string());

        // Split "pkg@version" into name and version.
        let (name, version) = match pkg_id.rfind('@') {
            Some(pos) => (&pkg_id[..pos], &pkg_id[pos + 1..]),
            None => (pkg_id.as_str(), ""),
        };

        let key = license_text.clone().unwrap_or_else(|| license_id.clone());
        let entry = groups
            .entry(key)
            .or_insert_with(|| (license_id, license_text, Vec::new()));
        entry.2.push(LicenseDep {
            name: name.to_string(),
            version: version.to_string(),
        });
    }

    groups
        .into_values()
        .map(|(license_id, text, deps)| {
            let text = text.unwrap_or_else(|| {
                format!("(No license file found. SPDX identifier: {})", license_id)
            });
            LicenseGroup {
                license: license_id,
                text,
                dependencies: deps,
            }
        })
        .collect()
}
